<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TO-49MSFD2-D" ignored="0" name="Default test" tests="1" failures="1" timestamp="2020-01-18T11:24:48 IST" time="68.31" errors="0">
  <testcase name="createRealEstateBrokerSupplier" time="68.273" classname="com.techouts.fanniemae.testcases.RealEstateBrokerSupplierCreationTest">
    <failure type="com.techouts.fanniemae.exceptions.FannieMaeBusinessException" message="throwing exception to make sure capturing testcase result to testNG">
      <![CDATA[com.techouts.fanniemae.exceptions.FannieMaeBusinessException: throwing exception to make sure capturing testcase result to testNG
at com.fanniemae.automation.test.AbstractTest.performPostExceptionProcess(AbstractTest.java:236)
at com.techouts.fanniemae.testcases.RealEstateBrokerSupplierCreationTest.createRealEstateBrokerSupplier(RealEstateBrokerSupplierCreationTest.java:126)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.techouts.fanniemae.exceptions.FannieMaeBusinessException: unable to perform logout operation in TestCase[CreateRealEstateBrokerSupplier].
at com.fanniemae.automation.test.page.actions.HomePageActions.logout(HomePageActions.java:129)
at com.fanniemae.automation.test.AbstractTest.performPostExceptionProcess(AbstractTest.java:233)
... 29 more
]]>
    </failure>
  </testcase> <!-- createRealEstateBrokerSupplier -->
</testsuite> <!-- Default test -->
